apiVersion: v1
kind: Service
metadata:
  name: deis-builder
  labels:
    heritage: deis
  annotations:
{{- if .Values.global.use_native_ingress }}
    external-dns.alpha.kubernetes.io/hostname: deis-builder.{{ .Values.platform_domain }}
{{- end }}
spec:
  ports:
    - name: ssh
      port: 2222
      targetPort: 2223
  selector:
    app: deis-builder
{{ if .Values.global.use_native_ingress }}
  type: "LoadBalancer"
{{ end }}
