org: "hephy"
pull_policy: "Always"
docker_tag: v2.13.7
# limits_cpu: "100m"
# limits_memory: "50Mi"
# builder_pod_node_selector: "disk:ssd"
# git_lock_timeout: 10 # number of minutes you want to wait to git push again to the same repository (default 10)

global:
  # Experimental feature to toggle using kubernetes ingress instead of the Hephy router.
  #
  # Valid values are:
  # - true: The hephy controller will now create Kubernetes ingress rules for each app, and ingress rules will automatically be created for the controller itself.
  # - false: The default mode, and the default behavior of Hephy workflow.
  use_native_ingress: false
  # Role-Based Access Control for Kubernetes >= 1.5
  use_rbac: false
